# cloudbuild.yaml
steps:
  # build & push the container image
- name: "gcr.io/kunal-862dc/executor:latest"
  args: ["--cache=true", "--cache-ttl=48h", "--destination=gcr.io/kunal-862dc/todo:latest"]
  # Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args: ['beta', 'run', 'deploy', 'todo', '--image', 'gcr.io/kunal-862dc/todo:latest', '--region', 'asia-south1', '--allow-unauthenticated', '--platform', 'managed']